"""Dry run, execute, verify, undo. Readme.md section 20.1.

The escape tests next door prove an agent cannot reach anybody else's rows.
These prove the other half of the connector interface actually works on the
rows it *can* reach: that a dry run predicts what execution does, that a write
can be seen afterwards by the person who made it, and that it can be put back.

This gets its own app. The escape tests assert that nothing moved, and a test
that commits writes has no business sharing a database with them.
"""

from __future__ import annotations

import uuid

import pytest
import pytest_asyncio

from control_plane.models import Action
from gateway.connectors.base import DryRun
from gateway.connectors.postgres import PostgresConnector, SchemaCatalog
from gateway.policy import Limits
from tests.attack.conftest import build
from tests.gateway.conftest import creds_for


@pytest_asyncio.fixture(scope="module")
async def app(gateway_admin):
    async with build(gateway_admin, "crm_chain") as built:
        yield built


@pytest.fixture
def writer(app):
    catalog = SchemaCatalog.from_graph(app.roles.schema, app.graph)
    return PostgresConnector(catalog=catalog, limits=Limits())


@pytest.fixture
def alice(app):
    return creds_for(app, "A")


def _action(tool, args, dry):
    """The stored record `undo` works from, built the way the pipeline stores
    it: contract 7.6's row, with the dry run's before and after images."""
    return Action(tool=tool, args=args, dry_run=dry.as_json())


async def _name(app, row_id):
    return await app.admin.fetchval(
        f'SELECT name FROM "{app.roles.schema}".customers WHERE id = $1', row_id
    )


async def test_an_update_happens_once_and_can_be_put_back(app, writer, alice):
    mine = app.plan.one_owned_by("customers", "A")
    args = {
        "table": "customers",
        "filters": [{"column": "id", "op": "=", "value": str(mine.key[0])}],
        "values": {"name": "renamed by her own agent"},
    }
    was = await _name(app, mine.key[0])

    dry = await writer.dry_run(alice, "db_update", args)
    assert dry.affected == 1
    assert dry.before[0]["name"] == was
    assert dry.after[0]["name"] == "renamed by her own agent"

    result = await writer.execute(alice, "db_update", args, dry)
    assert result.ok and result.affected == 1
    assert await _name(app, mine.key[0]) == "renamed by her own agent"

    assert await writer.verify(alice, "db_update", args, result)

    undone = await writer.undo(alice, _action("db_update", args, dry))
    assert undone.ok, undone.reason
    assert await _name(app, mine.key[0]) == was


async def test_an_update_that_already_happened_is_not_done_twice(app, writer, alice):
    """The approval was for the rows the dry run found. Running it against a
    database that has moved on is refused, not retried."""
    mine = app.plan.one_owned_by("customers", "A")
    args = {
        "table": "customers",
        "filters": [{"column": "id", "op": "=", "value": str(mine.key[0])}],
        "values": {"name": "first"},
    }
    dry = await writer.dry_run(alice, "db_update", args)

    await app.admin.execute(
        f'UPDATE "{app.roles.schema}".customers SET name = $1 WHERE id = $2',
        "somebody else got there first",
        mine.key[0],
    )

    result = await writer.execute(alice, "db_update", args, dry)
    assert not result.ok
    assert "changed since" in (result.reason or "")
    assert await _name(app, mine.key[0]) == "somebody else got there first"


async def test_a_created_row_belongs_to_its_creator_and_can_be_removed(
    app, writer, alice
):
    """The row's id is generated by the database, so the dry run cannot know
    it. What the approval is bound to is the values that were asked for."""
    args = {
        "table": "customers",
        "values": {"rep_id": str(app.plan.user_ids["A"]), "name": "a new customer"},
    }
    dry = await writer.dry_run(alice, "db_create", args)
    assert dry.affected == 1

    result = await writer.execute(alice, "db_create", args, dry)
    assert result.ok, result.reason
    created = result.rows[0]["id"]
    assert await _name(app, uuid.UUID(created)) == "a new customer"

    assert await writer.verify(alice, "db_create", args, result)

    # Undo works from what was really written, not from the dry run's row.
    undone = await writer.undo(
        alice, _action("db_create", args, DryRun(affected=1, after=result.rows))
    )
    assert undone.ok, undone.reason
    assert await _name(app, uuid.UUID(created)) is None


async def test_a_delete_is_undone_by_putting_the_row_back(app, writer, alice):
    args = {
        "table": "customers",
        "values": {"rep_id": str(app.plan.user_ids["A"]), "name": "doomed"},
    }
    made = await writer.execute(
        alice, "db_create", args, await writer.dry_run(alice, "db_create", args)
    )
    row_id = made.rows[0]["id"]

    doomed = {
        "table": "customers",
        "filters": [{"column": "id", "op": "=", "value": row_id}],
    }
    dry = await writer.dry_run(alice, "db_delete", doomed)
    assert dry.affected == 1 and dry.after == []

    result = await writer.execute(alice, "db_delete", doomed, dry)
    assert result.ok
    assert await writer.verify(alice, "db_delete", doomed, result)
    assert await _name(app, uuid.UUID(row_id)) is None

    undone = await writer.undo(alice, _action("db_delete", doomed, dry))
    assert undone.ok, undone.reason
    assert await _name(app, uuid.UUID(row_id)) == "doomed"


async def test_undo_refuses_when_somebody_else_has_changed_the_row(app, writer, alice):
    mine = app.plan.one_owned_by("customers", "A")
    args = {
        "table": "customers",
        "filters": [{"column": "id", "op": "=", "value": str(mine.key[0])}],
        "values": {"name": "the agent's version"},
    }
    dry = await writer.dry_run(alice, "db_update", args)
    assert (await writer.execute(alice, "db_update", args, dry)).ok

    await app.admin.execute(
        f'UPDATE "{app.roles.schema}".customers SET name = $1 WHERE id = $2',
        "and then a person edited it",
        mine.key[0],
    )

    undone = await writer.undo(alice, _action("db_update", args, dry))
    assert not undone.ok
    assert "changed since" in (undone.reason or "")
    assert await _name(app, mine.key[0]) == "and then a person edited it"
