"""Hand-written expected graphs for the schema fixtures. Readme.md section 8 M3.

Written by reading `fixtures/schemas/*.sql`, never by printing what the
introspector produced. If the introspector disagrees with a graph here, the
introspector is the thing that is wrong until proven otherwise.

Two conventions that are Postgres', not ours, and are relied on below:
  - autogenerated constraint names: `<table>_pkey`, `<table>_<cols>_key`,
    `<table>_<col>_check`, `<table>_<cols>_fkey`; composite keys list every
    column.
  - `default` and `type` are rendered with the app schema on `search_path`, so
    nothing here is schema-qualified. That is what keeps `schema_hash` stable
    across the scratch schema being called something different every run.
"""

from __future__ import annotations


def _col(name, type_, *, nullable=False, default=None):
    return {"name": name, "type": type_, "nullable": nullable, "default": default}


def _table(columns, *, primary_key, unique=(), checks=(), foreign_keys=()):
    return {
        "columns": columns,
        "primary_key": list(primary_key),
        "unique": [dict(u) for u in unique],
        "checks": [dict(c) for c in checks],
        "foreign_keys": [dict(f) for f in foreign_keys],
        # Fixtures are introspected straight after migration, before the kernel
        # touches anything.
        "rls_enabled": False,
        "rls_forced": False,
    }


def _fk(name, columns, references, referenced_columns):
    return {
        "name": name,
        "columns": list(columns),
        "references": references,
        "referenced_columns": list(referenced_columns),
    }


_UUID_PK = _col("id", "uuid", default="gen_random_uuid()")


FLAT_TODO = {
    "version": 1,
    "tables": {
        "users": _table(
            [
                _UUID_PK,
                _col("email", "text"),
                _col("created_at", "timestamp with time zone", default="now()"),
            ],
            primary_key=["id"],
            unique=[{"name": "users_email_key", "columns": ["email"]}],
        ),
        "todos": _table(
            [
                _UUID_PK,
                _col("owner_id", "uuid"),
                _col("title", "text"),
                _col("done", "boolean", default="false"),
                _col("priority", "integer", default="0"),
            ],
            primary_key=["id"],
            checks=[
                {
                    "name": "todos_priority_check",
                    "expression": "CHECK (((priority >= 0) AND (priority <= 5)))",
                }
            ],
            foreign_keys=[_fk("todos_owner_id_fkey", ["owner_id"], "users", ["id"])],
        ),
    },
    "enums": {},
    "views": {},
    "functions": [],
    "policies": {},
}


CRM_CHAIN = {
    "version": 1,
    "tables": {
        "users": _table(
            [_UUID_PK, _col("email", "text"), _col("name", "text", nullable=True)],
            primary_key=["id"],
            unique=[{"name": "users_email_key", "columns": ["email"]}],
        ),
        "customers": _table(
            [_UUID_PK, _col("rep_id", "uuid"), _col("name", "text")],
            primary_key=["id"],
            foreign_keys=[_fk("customers_rep_id_fkey", ["rep_id"], "users", ["id"])],
        ),
        "orders": _table(
            [
                _UUID_PK,
                _col("customer_id", "uuid"),
                _col("placed_at", "timestamp with time zone", default="now()"),
            ],
            primary_key=["id"],
            foreign_keys=[
                _fk("orders_customer_id_fkey", ["customer_id"], "customers", ["id"])
            ],
        ),
        "invoices": _table(
            [
                _UUID_PK,
                _col("order_id", "uuid"),
                _col("amount", "numeric(12,2)"),
                _col("status", "invoice_status", default="'draft'::invoice_status"),
            ],
            primary_key=["id"],
            checks=[
                {
                    "name": "invoices_amount_check",
                    "expression": "CHECK ((amount >= (0)::numeric))",
                }
            ],
            foreign_keys=[_fk("invoices_order_id_fkey", ["order_id"], "orders", ["id"])],
        ),
        "plans": _table(
            [_col("code", "text"), _col("monthly", "numeric(12,2)")],
            primary_key=["code"],
        ),
        "audit_log": _table(
            [
                _col("id", "bigint", default="nextval('audit_log_id_seq'::regclass)"),
                _col("at", "timestamp with time zone", default="now()"),
                _col("actor", "text"),
                _col("detail", "text", nullable=True),
            ],
            primary_key=["id"],
        ),
    },
    "enums": {"invoice_status": ["draft", "sent", "paid", "void"]},
    "views": {},
    "functions": [],
    "policies": {},
}


MESSY = {
    "version": 1,
    "tables": {
        "accounts": _table(
            [_UUID_PK, _col("email", "text")],
            primary_key=["id"],
            unique=[{"name": "accounts_email_key", "columns": ["email"]}],
        ),
        "profiles": _table(
            [_UUID_PK, _col("display_name", "text")],
            primary_key=["id"],
        ),
        "projects": _table(
            [
                _UUID_PK,
                _col("owner_id", "uuid"),
                _col("created_by", "uuid"),
                _col("name", "text"),
            ],
            primary_key=["id"],
            # Two candidate owner columns. Derivation must ask, not pick.
            foreign_keys=[
                _fk("projects_created_by_fkey", ["created_by"], "accounts", ["id"]),
                _fk("projects_owner_id_fkey", ["owner_id"], "accounts", ["id"]),
            ],
        ),
        "project_members": _table(
            [
                _col("project_id", "uuid"),
                _col("account_id", "uuid"),
                _col("role", "text", default="'member'::text"),
            ],
            primary_key=["project_id", "account_id"],
            foreign_keys=[
                _fk(
                    "project_members_account_id_fkey",
                    ["account_id"],
                    "accounts",
                    ["id"],
                ),
                _fk(
                    "project_members_project_id_fkey",
                    ["project_id"],
                    "projects",
                    ["id"],
                ),
            ],
        ),
        "tasks": _table(
            [
                _UUID_PK,
                _col("project_id", "uuid"),
                _col("assignee_id", "uuid", nullable=True),
                _col("title", "text"),
            ],
            primary_key=["id"],
            foreign_keys=[
                _fk("tasks_assignee_id_fkey", ["assignee_id"], "accounts", ["id"]),
                _fk("tasks_project_id_fkey", ["project_id"], "projects", ["id"]),
            ],
        ),
        "settings": _table(
            [_col("key", "text"), _col("value", "text")],
            primary_key=["key"],
        ),
        "legacy_docs": _table(
            [
                _col("tenant_id", "uuid"),
                _col("doc_no", "integer"),
                _col("title", "text"),
            ],
            primary_key=["tenant_id", "doc_no"],
        ),
        "legacy_notes": _table(
            [
                _UUID_PK,
                _col("tenant_id", "uuid"),
                _col("doc_no", "integer"),
                _col("body", "text"),
            ],
            primary_key=["id"],
            foreign_keys=[
                _fk(
                    "legacy_notes_tenant_id_doc_no_fkey",
                    ["tenant_id", "doc_no"],
                    "legacy_docs",
                    ["tenant_id", "doc_no"],
                )
            ],
        ),
    },
    "enums": {},
    "views": {
        "reports": {"security_invoker": False},
        "safe_reports": {"security_invoker": True},
    },
    "functions": [
        {"name": "bump_task_count", "arguments": "p uuid", "security_definer": True}
    ],
    "policies": {},
}


BY_FIXTURE = {
    "flat_todo": FLAT_TODO,
    "crm_chain": CRM_CHAIN,
    "messy": MESSY,
}
