"""Safe SQL rendering for the kernel. Readme.md section 9.

Roles, schemas, tables and columns cannot be passed as bind parameters, so they
are quoted here instead. Every identifier that reaches a template goes through
`quote_ident`, and templates are rendered by explicit key substitution so a
typo raises rather than silently leaving a hole in the SQL.

Nothing in this module ever interpolates a value the database could have
treated as a bind parameter.
"""

from __future__ import annotations

import re
import secrets
from functools import lru_cache
from pathlib import Path
from typing import Mapping, Sequence

_SQL_DIR = Path(__file__).parent / "sql"

# Deliberately narrow. App ids are generated by the control plane, never by a
# builder, and the derived role names must fit inside Postgres' 63 byte limit.
_APP_ID = re.compile(r"^app_[a-z0-9_]{1,40}$")

_PLACEHOLDER = re.compile(r"\{([a-z_]+)\}")

# Types a principal key is allowed to have. Anything else is refused rather
# than cast, because this string lands in a function signature.
_KEY_TYPES = frozenset({"uuid", "text", "bigint", "integer"})

_PASSWORD_ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"


def validate_app_id(app_id: str) -> str:
    if not _APP_ID.fullmatch(app_id or ""):
        raise ValueError(
            f"invalid app id {app_id!r}: expected app_<lowercase alnum/underscore>"
        )
    return app_id


def key_type(name: str) -> str:
    if name not in _KEY_TYPES:
        raise ValueError(
            f"unsupported principal key type {name!r}; allowed: {sorted(_KEY_TYPES)}"
        )
    return name


def quote_ident(name: str) -> str:
    """Quote an identifier the way `format('%I', ...)` would.

    Always quotes, so a reserved word or a name containing a quote, a semicolon
    or whitespace is inert.
    """
    if not isinstance(name, str) or not name:
        raise ValueError(f"identifier must be a non-empty string, got {name!r}")
    if "\x00" in name:
        raise ValueError("identifier contains a null byte")
    if len(name.encode()) > 63:
        raise ValueError(f"identifier {name!r} exceeds Postgres' 63 byte limit")
    return '"' + name.replace('"', '""') + '"'


def quote_literal(value: str) -> str:
    """Quote a string literal. Only used for passwords in CREATE ROLE, which
    cannot take bind parameters."""
    if not isinstance(value, str):
        raise ValueError(f"literal must be a string, got {type(value).__name__}")
    if "\x00" in value:
        raise ValueError("literal contains a null byte")
    return "'" + value.replace("'", "''") + "'"


def generate_password(length: int = 48) -> str:
    """Alphanumeric only: these travel through DSNs and Secrets Manager, and a
    password that needs escaping somewhere is a password that will break there."""
    return "".join(secrets.choice(_PASSWORD_ALPHABET) for _ in range(length))


def _hop_pairs(hop: Mapping[str, str]) -> list[tuple[str, str]]:
    """The (child column, parent column) pairs of one path hop.

    Contract 7.2 spells a single-column hop `column`/`to_column`; a composite
    hop carries `columns`/`to_columns` instead. A hop that has neither is a bug
    upstream and must not render as an empty join condition.
    """
    if "column" in hop:
        return [(hop["column"], hop["to_column"])]
    pairs = list(zip(hop["columns"], hop["to_columns"], strict=True))
    if not pairs:
        raise ValueError(f"path hop joins on no columns: {hop!r}")
    return pairs


def fk_chain_expression(
    *, schema: str, table: str, path: Sequence[Mapping[str, str]], admin: str = ""
) -> str:
    """Build the EXISTS expression for a derived path. Readme.md section 9.3.

    Takes raw identifiers and quotes them here, unlike the other renderers,
    because the path comes straight out of the access model and every name in
    it has to be quoted the same way. Aliases are generated (`a1`, `a2`, ...)
    so a joined table can never collide with the policy's own table.

    For `invoices -> orders -> customers -> users`:

        EXISTS (SELECT 1 FROM "s"."orders" AS "a1"
                JOIN "s"."customers" AS "a2" ON "a2"."id" = "a1"."customer_id"
                WHERE "a1"."id" = "s"."invoices"."order_id"
                  AND "a2"."rep_id" = "s".vd_user_id())
    """
    if len(path) < 2:
        raise ValueError(
            "fk_chain needs at least two hops; a single hop is owner_column"
        )

    s = quote_ident(schema)
    base = f"{s}.{quote_ident(table)}"
    alias = [quote_ident(f"a{i + 1}") for i in range(len(path) - 1)]

    # The last hop is the one that lands on the principal, and its child side is
    # the final alias. It must be a single column: the principal's key is.
    final = _hop_pairs(path[-1])
    if len(final) != 1:
        raise ValueError(
            "the last hop of a chain must join on one column, the principal key"
        )

    froms = f"{s}.{quote_ident(path[0]['to'])} AS {alias[0]}"
    for i in range(1, len(path) - 1):
        on = " AND ".join(
            f"{alias[i]}.{quote_ident(parent)} = {alias[i - 1]}.{quote_ident(child)}"
            for child, parent in _hop_pairs(path[i])
        )
        froms += f" JOIN {s}.{quote_ident(path[i]['to'])} AS {alias[i]} ON {on}"

    where = [
        f"{alias[0]}.{quote_ident(parent)} = {base}.{quote_ident(child)}"
        for child, parent in _hop_pairs(path[0])
    ]
    where.append(f"{alias[-1]}.{quote_ident(final[0][0])} = {s}.vd_user_id()")

    return (
        f"EXISTS (SELECT 1 FROM {froms} WHERE {' AND '.join(where)}){admin}"
    )


@lru_cache(maxsize=None)
def _read(name: str) -> str:
    path = (_SQL_DIR / name).resolve()
    if not path.is_relative_to(_SQL_DIR.resolve()):
        raise ValueError(f"template {name!r} escapes the sql directory")
    return path.read_text(encoding="utf-8")


def render(name: str, **values: str) -> str:
    """Substitute `{placeholders}` in a template file.

    Callers must pass already-quoted identifiers. Missing or unused keys raise,
    so a renamed placeholder can never render as an empty string.
    """
    sql = _read(name)
    seen: set[str] = set()
    missing: set[str] = set()

    def substitute(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            missing.add(key)
            return match.group(0)
        seen.add(key)
        return values[key]

    out = _PLACEHOLDER.sub(substitute, sql)

    if missing:
        raise KeyError(f"{name} needs values for: {sorted(missing)}")
    unused = set(values) - seen
    if unused:
        raise KeyError(f"{name} does not use: {sorted(unused)}")
    return out
