"""gateway tables for M10

Revision ID: d5a5c286a430
Revises: da623ba51bb9
Create Date: 2026-09-25 22:43:41.634181
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd5a5c286a430'
down_revision = 'da623ba51bb9'
branch_labels = None
depends_on = None

# Readme.md 19.6 gives the gateway INSERT and SELECT on `audit_log` and nothing
# else. That is a grant, and a grant is one mistake away from being wider than
# it was meant to be, so the table refuses the two statements itself as well.
# Nothing in the product ever updates or deletes an audit row.
_APPEND_ONLY_FUNCTION = """
CREATE OR REPLACE FUNCTION vd_control.audit_log_is_append_only()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'vd_control.audit_log is append only'
        USING ERRCODE = 'insufficient_privilege';
END;
$$
"""

_APPEND_ONLY_TRIGGER = """
CREATE TRIGGER audit_log_append_only
BEFORE UPDATE OR DELETE ON vd_control.audit_log
FOR EACH ROW EXECUTE FUNCTION vd_control.audit_log_is_append_only()
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='vd_control'
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action_id'], unique=False, schema='vd_control')
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_kill_switch', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_global_settings_singleton'),
    sa.PrimaryKeyConstraint('id'),
    schema='vd_control'
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('acts_for_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_status'),
    sa.ForeignKeyConstraint(['acts_for_user_id'], ['vd_control.app_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['app_id'], ['vd_control.apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'name', name='uq_agents_name'),
    schema='vd_control'
    )
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('acts_for', sa.UUID(), nullable=False),
    sa.Column('connector', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('dry_run', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('undo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('received', 'denied', 'dry_run_done', 'pending_approval', 'approved', 'rejected', 'expired', 'executing', 'verified', 'failed', 'rolled_back', 'undo_failed', 'undone')", name='ck_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['vd_control.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['app_id'], ['vd_control.apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vd_control'
    )
    op.create_index('ix_actions_agent', 'actions', ['agent_id', 'created_at'], unique=False, schema='vd_control')
    op.create_index('ix_actions_app', 'actions', ['app_id', 'created_at'], unique=False, schema='vd_control')
    op.create_table('agent_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['vd_control.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vd_control'
    )
    op.create_table('agent_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('policy_yaml', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('high_risk_ack', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['vd_control.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_policies_version'),
    schema='vd_control'
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['vd_control.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vd_control'
    )
    op.add_column('deployments', sa.Column('schema_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='vd_control')
    # ### end Alembic commands ###

    op.execute(_APPEND_ONLY_FUNCTION)
    op.execute(_APPEND_ONLY_TRIGGER)
    # The kill switch has to have somewhere to be read from before the first
    # agent exists, and "no row" must never be read as "switch is off".
    op.execute(
        "INSERT INTO vd_control.global_settings (id, agent_kill_switch)"
        " VALUES (1, false)"
    )


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS vd_control.audit_log_is_append_only() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'schema_graph', schema='vd_control')
    op.drop_table('agent_sessions', schema='vd_control')
    op.drop_table('agent_policies', schema='vd_control')
    op.drop_table('agent_keys', schema='vd_control')
    op.drop_index('ix_actions_app', table_name='actions', schema='vd_control')
    op.drop_index('ix_actions_agent', table_name='actions', schema='vd_control')
    op.drop_table('actions', schema='vd_control')
    op.drop_table('agents', schema='vd_control')
    op.drop_table('global_settings', schema='vd_control')
    op.drop_index('ix_audit_log_action', table_name='audit_log', schema='vd_control')
    op.drop_table('audit_log', schema='vd_control')
    # ### end Alembic commands ###
