"""control plane tables for M7

Revision ID: da623ba51bb9
Revises: 
Create Date: 2026-09-25 16:12:37.342830
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'da623ba51bb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='vd_control'
    )
    op.create_table('apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('builder_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('subdomain', sa.Text(), nullable=False),
    sa.Column('repo', sa.Text(), nullable=False),
    sa.Column('installation_id', sa.Text(), nullable=True),
    sa.Column('stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('protection', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('agents_enabled', sa.Boolean(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('live_deployment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("protection IN ('unknown', 'protected', 'unprotected')", name='ck_protection'),
    sa.ForeignKeyConstraint(['builder_id'], ['vd_control.builders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', name='uq_apps_app_id'),
    sa.UniqueConstraint('subdomain', name='uq_apps_subdomain'),
    schema='vd_control'
    )
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('principal_key', sa.Text(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['vd_control.apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'email', name='uq_app_users_email'),
    schema='vd_control'
    )
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('image_digest', sa.Text(), nullable=True),
    sa.Column('schema_hash', sa.Text(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'building', 'awaiting_answers', 'awaiting_confirmation', 'verifying', 'blocked', 'deploying', 'live', 'superseded', 'error')", name='ck_status'),
    sa.ForeignKeyConstraint(['app_id'], ['vd_control.apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vd_control'
    )
    op.create_index('ix_deployments_app', 'deployments', ['app_id'], unique=False, schema='vd_control')
    op.create_table('access_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('model_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['vd_control.apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_id'], ['vd_control.deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', name='uq_access_models_deployment'),
    schema='vd_control'
    )
    op.create_table('build_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phase IN ('plan', 'verify')", name='ck_phase'),
    sa.ForeignKeyConstraint(['deployment_id'], ['vd_control.deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_build_tokens_hash'),
    schema='vd_control'
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'waiting', 'done', 'failed')", name='ck_status'),
    sa.ForeignKeyConstraint(['app_id'], ['vd_control.apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_id'], ['vd_control.deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vd_control'
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_after'], unique=False, schema='vd_control')
    op.create_table('verification_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('runtime', 'agent')", name='ck_verification_role'),
    sa.ForeignKeyConstraint(['deployment_id'], ['vd_control.deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', 'role', name='uq_verification_run'),
    schema='vd_control'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_runs', schema='vd_control')
    op.drop_index('ix_jobs_claim', table_name='jobs', schema='vd_control')
    op.drop_table('jobs', schema='vd_control')
    op.drop_table('build_tokens', schema='vd_control')
    op.drop_table('access_models', schema='vd_control')
    op.drop_index('ix_deployments_app', table_name='deployments', schema='vd_control')
    op.drop_table('deployments', schema='vd_control')
    op.drop_table('app_users', schema='vd_control')
    op.drop_table('apps', schema='vd_control')
    op.drop_table('builders', schema='vd_control')
    # ### end Alembic commands ###
